# Generated by Django 4.0.5 on 2022-06-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonebiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default='No image', upload_to='image'),
        ),
    ]
