# Generated by Django 4.0.5 on 2022-06-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonebiz', '0003_alter_service_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='image')),
                ('content', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('published_date', models.DateTimeField()),
                ('author', models.CharField(max_length=100)),
                ('authors_photo', models.ImageField(upload_to='image')),
            ],
        ),
    ]
